import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./components/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><header className="flex justify-between items-center p-4 bg-gray-100 dark:bg-gray-800"> <Navigation /></header>
        {/* <p>Wecome to next.js 15 crush course</p> */}
        {children}
        <footer className="flex justify-center items-center p-4 bg-gray-100 dark:bg-gray-800">
          <p className="text-sm text-gray-600 dark:text-gray-400">
            © 2023 Next.js Crash Course
          </p>
        </footer>
      </body>
    </html>
  );
}
